"""add access and refresh tokens tables

Revision ID: 69c48b968ed2
Revises: aab915c23e8c
Create Date: 2025-10-19 21:41:33.255808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c48b968ed2'
down_revision: Union[str, Sequence[str], None] = 'aab915c23e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('googleId', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('accessToken', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('googleId', 'accessToken')
    )
    op.create_table('refresh_tokens',
    sa.Column('googleId', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('refreshToken', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('googleId', 'refreshToken')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
