"""recreate access_tokens table

Revision ID: 8b828b92cc1e
Revises: 69c48b968ed2
Create Date: 2025-10-19 21:49:42.134311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b828b92cc1e'
down_revision: Union[str, Sequence[str], None] = '69c48b968ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('googleId', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('accessToken', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('accessToken')
    )
    op.create_table('refresh_tokens',
    sa.Column('googleId', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('refreshToken', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('refreshToken')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
