"""Added tables: members, rooms

Revision ID: 9f0f160b8dcd
Revises: 8b828b92cc1e
Create Date: 2025-11-03 12:16:01.528316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0f160b8dcd'
down_revision: Union[str, Sequence[str], None] = '8b828b92cc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('googleId', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('role', sa.Enum('host', 'user', name='roleenum'), nullable=False),
    sa.Column('roomId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('googleId')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('access_tokens', 'googleId',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=False)
    op.alter_column('refresh_tokens', 'googleId',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'googleId',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=True)
    op.alter_column('access_tokens', 'googleId',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=True)
    op.drop_table('rooms')
    op.drop_table('members')
    # ### end Alembic commands ###
