"""update users table to prod 1

Revision ID: bc39fac168c9
Revises: cd6cc7a52f51
Create Date: 2025-10-16 22:50:51.260065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39fac168c9'
down_revision: Union[str, Sequence[str], None] = 'cd6cc7a52f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'googleId',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=30, scale=0),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'googleId',
               existing_type=sa.Numeric(precision=30, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
