"""update users table to prod 1

Revision ID: cd6cc7a52f51
Revises: 2a39f5c75387
Create Date: 2025-10-16 22:47:43.820342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6cc7a52f51'
down_revision: Union[str, Sequence[str], None] = '2a39f5c75387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('googleId', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'googleId')
    # ### end Alembic commands ###
